title: "Mi Web de Writeups"
baseurl: ""       # si usas TU_REPO.github.io
url: "https://nebotp.github.io/"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
theme: jekyll-theme-slate     # o deja vacío si usas tu propio CSS
